### ISSUE TITLE
Buckaroo Gateway not available

### ISSUE THREAD

**Issue by gisostallenberg** [thephpleague/omnipay-buckaroo#10]
The README says:

> The following gateways are provided by this package:
* Buckaroo
* Buckaroo_Ideal
* Buckaroo_PayPal

This [would imply](https://github.com/thephpleague/omnipay-common/blob/44ef8860a12ce85eabb3c076b34f007277ec2336/src/Omnipay/Common/Helper.php#L112) a class \Omnipay\Buckaroo\Gateway exists, which is not true.

I think Buckaroo_CreditCard is meant instead.

I can provide a PR fixing the README.

**Comment by delatbabel** [comment]
Yes a PR would be appreciated. That's how bugs get fixed. :)
