### ISSUE TITLE
buckaroo creditcard gateway currently only supports visa

### ISSUE THREAD

**Issue by silvano-a** [thephpleague/omnipay-buckaroo#14]
Right now credit card provider 'visa' is hardcoded.
https://github.com/thephpleague/omnipay-buckaroo/blob/master/src/Message/CreditCardPurchaseRequest.php#L13
buckaroo also supports Mastercard, and American express.

i made a PR which adds support for mastercard and american express
https://github.com/thephpleague/omnipay-buckaroo/pull/15

**Comment by delatbabel** [comment]
Merged.
