### ISSUE TITLE
Current release is very outdated

### ISSUE THREAD

**Issue by silvano-a** [thephpleague/omnipay-buckaroo#20]
the current release is behind : 
4 ideal issuers,
3 gateways, 
2 responses,
and in the current release only VISA is supported as credit card.

when can we expect a new release? all the PRs that are in right now make this for a stable one.

**Comment by silvano-a** [comment]
@delatbabel

**Comment by delatbabel** [comment]
Normally when I merge a PR I ask the submitter to verify that it works in production before I tag for release. I can't test on the actual buckaroo production gateway so if you (or someone else) can confirm that the dev-master works on a production account then I will tag.

**Comment by silvano-a** [comment]
just finished testing. 
dev-master works, i tested all functions committed since the previous release.

**Comment by delatbabel** [comment]
Tagged and released.

**Comment by silvano-a** [comment]
thanks! appreciate it
